spring:
  application:
    name: server

besu:
  rpc-url: ${BESU_RPC_URL:http://localhost:8545}
  chain-id: ${BESU_CHAIN_ID:1337}

token:
  contract-address: ${TOKEN_CONTRACT_ADDRESS:}
  signer-private-key: ${BESU_SIGNER_PRIVATE_KEY:}
